#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Oct 03, 2022 08:44:20 PM +1100  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import 2dFireMenuBuilder_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("576x353+750+345")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("2D Fire Excel Convertor")
        top.configure(background="#d9d9d9")

        self.top = top

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.116, rely=0.221, height=27, relwidth=0.563)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.729, rely=0.51, height=24, width=107)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=lambda :2dFireMenuBuilder_support.print("start"))
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start''')

        self.TButton_FileSelector = tk.Button(self.top)
        self.TButton_FileSelector.place(relx=0.712, rely=0.227, height=24
                , width=117)
        self.TButton_FileSelector.configure(activebackground="beige")
        self.TButton_FileSelector.configure(activeforeground="black")
        self.TButton_FileSelector.configure(background="#d9d9d9")
        self.TButton_FileSelector.configure(command=lambda :2dFireMenuBuilder_support.print("Select"))
        self.TButton_FileSelector.configure(compound='left')
        self.TButton_FileSelector.configure(disabledforeground="#a3a3a3")
        self.TButton_FileSelector.configure(foreground="#000000")
        self.TButton_FileSelector.configure(highlightbackground="#d9d9d9")
        self.TButton_FileSelector.configure(highlightcolor="black")
        self.TButton_FileSelector.configure(pady="0")
        self.TButton_FileSelector.configure(text='''Select 2DFire Excel''')

def start_up():
    2dFireMenuBuilder_support.main()

if __name__ == '__main__':
    2dFireMenuBuilder_support.main()




